repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: cargo-test
        name: Cargo Test
        description: Run cargo test to ensure all tests pass
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-fmt
        name: Cargo Format
        description: Run cargo fmt to ensure consistent code formatting
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: Cargo Clippy
        description: Run cargo clippy to ensure code quality
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false